language: c
sudo: required
dist: bionic
matrix:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y linux-headers-4.15.0-20-generic linux-headers-4.15.0-20
    - sudo ln -s /usr/src/4.15.0-20-generic /lib/modules/4.15.0-20-generic/build
script:
    - make
